---
name: CI/CD
on: [push, pull_request]
jobs:
  build:
    name: Build and test
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout master
      uses: actions/checkout@v1.2.0
    - name: Build and test
      run: docker/build.sh
